### ISSUE TITLE
请在minimal加入额外功能

### ISSUE THREAD

**Issue by lyricusark** [biliwala/nanopi-openwrt#1]
大佬能否在R2Sminimal加入zerotier、transmission和argon外观。本人太小白了，fork了都编译不来。

**Comment by biliwala** [comment]
klever1988/nanopi-openwrt#36

**Comment by biliwala** [comment]
**[R2S_Minimal_ROM.zip](https://github.com/biliwala/nanopi-openwrt/suites/2732341539/artifacts/60360482)**
[R2S_Package.zip](https://github.com/biliwala/nanopi-openwrt/suites/2732341539/artifacts/60360483)

**Comment by lyricusark** [comment]
感谢DALAO指点和提供小白定制版，另外fork的也终于跑通了，只是TR还有点问题：我在minimal_config.seed里增加了一段CONFIG_PACKAGE_luci-app-transmission=y，运行后管理界面有选项卡，但实际TR没有运行。请问是还需要添加什么内容吗？

**Comment by biliwala** [comment]
https://3mile.github.io/archives/2018/10/27/
